name: gabutdm
version: "1.5.1"
grade: stable
base: core20
summary: Simple and Faster Download Manager
description: |
    Gabutakut Download Manager application that can download Metallink Magnetlink Torrents URIs using Aria2c and,
    an application that has a local server service interface.
    can also accept file transfers from smartphones.
    Made with love and sleep deprivation. :D

confinement: strict
parts:
  gabutdm:
    after: [desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/gabutakut/gabutdm.git
    override-build: |
        snapcraftctl build
        sed -i -E 's|^(Icon[^=]*)=.*|\1=/usr/share/icons/hicolor/128x128/apps/com.github.gabutakut.gabutdm.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/com.github.gabutakut.gabutdm.desktop
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
        - libsoup2.4-dev
        - libcanberra-dev
        - libcairo2-dev
        - libsqlite3-dev
        - libqrencode-dev
        - libxtst-dev
        - libx11-dev
        - libgee-0.8-dev
        - libjson-glib-dev
        - libgdk-pixbuf2.0-dev
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
        - libcanberra0
        - libcogl-pango20
        - libcogl-path20
        - libcogl20
        - libevdev2
        - libinput10
        - libltdl7
        - libmtdev1
        - libogg0
        - liborc-0.4-0
        - aria2
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
apps:
  niki:
    command: usr/bin/com.github.gabutakut.gabutdm
    desktop: usr/share/applications/com.github.gabutakut.gabutdm.desktop
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
    slots: [ dbus-niki ]
slots:
  dbus-niki:
    interface: dbus
    bus: session
    name: com.github.gabutakut.gabutdm
plugs:
  gnome-3-36-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-36-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
