name: gabutdm
version: "2.6.0"
grade: stable
base: core22
summary: Simple and Faster Download Manager
description: |
    Gabut Download Manager application that can download all you need like Link URIs Metallink Magnetlink Torrents using Aria2c and,
    an application that has a local server service interface. also file transfers from smartphones.
    This application prioritizes convenience, full of features and an attractive appearance.

confinement: strict
parts:
  gabutdm:
    after: [desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/gabutakut/gabutdm.git
    override-build: |
        snapcraftctl build
        sed -i -E 's|^(Icon[^=]*)=.*|\1=/usr/share/icons/hicolor/scalable/apps/com.github.gabutakut.gabutdm.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/com.github.gabutakut.gabutdm.desktop
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
        - libsoup-3.0-dev
        - libcanberra-dev
        - libcairo2-dev
        - libsqlite3-dev
        - libqrencode-dev
        - libgee-0.8-dev
        - libjson-glib-dev
        - libgdk-pixbuf2.0-dev
        - libgtk-4-dev
        - libadwaita-1-dev
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
        - libcanberra0
        - libqrencode4
        - aria2
        - libhandy-1-0
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk4"]
    build-packages:
      - build-essential
      - libgtk-4-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
apps:
  gabutdm:
    command: usr/bin/com.github.gabutakut.gabutdm
    desktop: usr/share/applications/com.github.gabutakut.gabutdm.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - network
      - network-manager
      - unity7
      - home
    slots: [ dbus-gabutdm ]
slots:
  dbus-gabutdm:
    interface: dbus
    bus: session
    name: com.github.gabutakut.gabutdm
plugs:
  gnome-46-2404:
    default-provider: gnome-46-2404
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds
environment:
  GTK_USE_PORTAL: '1'
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform