name: Publish to AUR

on:
  release:
    types: [published]

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Get SHA256
        id: sha256
        run: |
          URL="https://github.com/gabutakut/gabutdm/archive/refs/tags/${{ steps.version.outputs.VERSION }}.tar.gz"
          SHA=$(curl -sL $URL | sha256sum | cut -d' ' -f1)
          echo "SHA256=$SHA" >> $GITHUB_OUTPUT

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: gabutdm
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ steps.version.outputs.VERSION }}"
          updpkgsums: true
