name: Build & Upload to PPA

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-make meson ninja-build valac \
          libgtk-4-dev libadwaita-1-dev libsoup-3.0-dev\
          libgee-0.8-dev libjson-glib-dev libqrencode-dev \
          libsqlite3-dev libcanberra-dev libgdk-pixbuf-2.0-dev \
          libcairo2-dev libavformat-dev libavcodec-dev libavutil-dev libaria2-0-dev libavdevice-dev \
          dput gnupg

      - name: Setup GPG
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | \
            gpg --batch --yes --pinentry-mode loopback --import
          gpg --batch --yes --pinentry-mode loopback \
            --command-fd 0 --expert --edit-key ${{ secrets.GPG_KEY_ID }} \
            <<< "trust
          5
          y
          quit"

      - name: Setup dput
        run: |
          cat > ~/.dput.cf << EOF
          [ppa]
          fqdn = ppa.launchpad.net
          method = ftp
          incoming = ~%(ppa)s/ubuntu
          login = anonymous
          allow_unsigned_uploads = 0
          EOF

      - name: Prepare source tarball
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          cd ..
          cp -r gabutdm gabutdm-${VERSION}
          tar -czf com.github.gabutakut.gabutdm_${VERSION}.orig.tar.gz gabutdm-${VERSION}

      - name: Build package
        env:
          DEBEMAIL: torik.habib@gmail.com
          DEBFULLNAME: torikulhabib
          GNUPGHOME: /home/runner/.gnupg
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          cd ../gabutdm-${VERSION}
          dch --newversion "${VERSION}" \
              --distribution noble \
              --force-distribution \
              -b \
              "Release ${VERSION}"
          chmod 644 debian/changelog debian/control debian/copyright
          chmod +x debian/rules
          dpkg-buildpackage -S -sa -d --no-sign
          echo "${{ secrets.GPG_PASSPHRASE }}" | \
            debsign -k${{ secrets.GPG_KEY_ID }} \
            --no-re-sign \
            -p"gpg --batch --yes --pinentry-mode loopback --passphrase ${{ secrets.GPG_PASSPHRASE }}" \
            ../*.changes

      - name: Upload to PPA
        run: |
          cd ..
          dput ppa:torik-habib/gabutdm *.changes