name: Build & Upload to PPA

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-make meson ninja-build valac \
          libgtk-4-dev libadwaita-1-dev libsoup-3.0-dev \
          libgee-0.8-dev libjson-glib-dev libqrencode-dev \
          libsqlite3-dev libcanberra-dev libgdk-pixbuf-2.0-dev \
          libcairo2-dev libavformat-dev libavcodec-dev libavutil-dev libaria2-0-dev \
          dput gnupg

      - name: Setup GPG
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --pinentry-mode loopback --import

      - name: Prepare source tarball
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          cd ..
          cp -r gabutdm gabutdm-${VERSION}
          # nama harus sesuai dengan Package di debian/changelog
          tar -czf com.github.gabutakut.gabutdm_${VERSION}.orig.tar.gz gabutdm-${VERSION}

      - name: Build package
        env:
          DEBEMAIL: torik.habib@gmail.com
          DEBFULLNAME: torikulhabib
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          cd ../gabutdm-${VERSION}
          yes | debuild -S -sa -d -k${{ secrets.GPG_KEY_ID }}

      - name: Upload to PPA
        run: |
          cd ..
          dput ppa:torikhabib/gabutdm *.changes
